language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest
    - WP_VERSION=3.4.2

matrix:
  exclude:
    - php: 5.4
      env: WP_VERSION=3.4.2

before_script:
    - curl -vL http://wordpress.org/extend/themes/download/p2.1.0.1.zip > /tmp/p2.zip
    - du -k /tmp/p2.zip

script: unzip /tmp/p2.zip

notifications:
    email:
        on_success: never
